language: android

env:
  - TERM=dump

env:
  matrix:
    - ANDROID_TARGET=android-18 ANDROID_ABI=armeabi-v7a
  global:
    - "ARTIFACTS_AWS_REGION=us-west-2"
    - "ARTIFACTS_S3_BUCKET=android-collapse-calendar-view"
    - secure: "lFeUSH2N+gGZyPBqI6LOBMnG8adjonjOohOvrz8nCcUV4Wn7/tHW7i4CzYDp/HUR+s3EBE7QFmBiifM4UTEnSvLpQUkfDS/86wfVlLUTnpiZqUWhLJIQFDZhiNJ3YGH197PG8+OZ1+BGzCFQXI1gt5pNFyMToCeP4cljL9DZdow="
    - secure: "kV99P8eZDRpfErIW+8i+Sz6pqyjsQ4VbtW8L/gg1lWSk/OVCz/BuJBfUpr8SIH/lDP5AsuP4vzWEkNuozbjv4whG3FCek73p1St3lSDZbestqbipshWfitkZwtz8KQnat5VnY35AeWKFstGKsDRtIIoaqLQnaqXqkyOF/DEypU0="

android:
  components:
    - build-tools-20.0.0
    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  # Emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
#  - "gem install fog-json"
#  - "gem install travis-artifacts"
  - ./ci/wait_for_emulator
  - adb shell input keyevent 82 &

after_script:
  - artifacts upload \
      --target-paths "artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER:artifacts/$TRAVIS_REPO_SLUG/$TRAVIS_COMMIT" \
#  - "travis-artifacts upload --path CollapseCalendarView/build/outputs/reports/androidTests/connected/"
